// packages/vue/src/runtime/components/iab-consent-banner.vue
<script setup lang="ts">
import { computed, toValue } from 'vue';
import { Teleport, Transition } from 'vue';
import { FocusScope } from 'reka-ui';
import type { GlobalVendorList, NonIABVendor } from '@c15t/schema/types';
import bannerStyles from '@c15t/styles/iab-consent-banner.module.css';
import {
	useConsentActiveUI,
	useConsentConfig,
	useConsentInit,
	useConsentIabSelection,
	type ConsentIabSelection,
} from '#c15t/composables';
import ConsentButton from './consent-button.vue';
import ConsentTag from './consent-tag.vue';
import { useConsentScrollLock } from '../composables/use-consent-scroll-lock';

const MAX_DISPLAY_ITEMS = 5;
const STANDALONE_PURPOSE_ID = 1;

const props = withDefaults(
	defineProps<{
		primaryButton?: 'reject' | 'accept' | 'customize';
	}>(),
	{
		primaryButton: 'customize',
	},
);

const activeUI = useConsentActiveUI();
const config = useConsentConfig();
const init = useConsentInit();
const iabSelection = useConsentIabSelection();

const initValue = computed(() => toValue(init));
const gvl = computed(() => initValue.value?.gvl ?? null);
const customVendors = computed(() => initValue.value?.customVendors ?? []);

const isOpen = computed(() => {
	const models = config.value.iabBannerModels;
	const model = initValue.value?.policy?.model;
	const matchesModel =
		!models?.length || (model !== undefined && models.includes(model));
	return (
		activeUI.value === 'banner' &&
		initValue.value?.policy?.model === 'iab' &&
		Boolean(gvl.value) &&
		matchesModel
	);
});
const disableAnimation = computed(() => Boolean(toValue(config).disableAnimation));

const showBanner = computed(
	() => isOpen.value && Boolean(gvl.value) && bannerSummary.value.isReady,
);

const iabT = computed(() => {
	const translations = toValue(init)?.translations?.translations as
		| { iab?: Record<string, unknown> }
		| undefined;
	return translations?.iab as {
		banner?: {
			title?: string;
			description?: string;
			partnersLink?: string;
			andMore?: string;
			legitimateInterestNotice?: string;
			scopeServiceSpecific?: string;
		};
		common?: {
			acceptAll?: string;
			rejectAll?: string;
			customize?: string;
		};
	} | undefined;
});

function resolveBannerSummary(gvlData: GlobalVendorList, vendors: NonIABVendor[]) {
	const vendorCount =
		Object.keys(gvlData.vendors).length + vendors.length;

	const purposesWithVendors = Object.entries(gvlData.purposes)
		.filter(([id]) =>
			Object.values(gvlData.vendors).some(
				(vendor) =>
					vendor.purposes?.includes(Number(id)) ||
					vendor.legIntPurposes?.includes(Number(id)),
			),
		)
		.map(([id, purpose]) => ({ id: Number(id), name: purpose.name }));

	const standalonePurpose = purposesWithVendors.find(
		(purpose) => purpose.id === STANDALONE_PURPOSE_ID,
	);
	const otherPurposes = purposesWithVendors.filter(
		(purpose) => purpose.id !== STANDALONE_PURPOSE_ID,
	);
	const otherPurposeIds = new Set(otherPurposes.map((purpose) => purpose.id));

	const stackScores: Array<{
		name: string;
		coveredPurposeIds: number[];
		score: number;
	}> = [];

	for (const stack of Object.values(gvlData.stacks || {})) {
		const coveredPurposeIds = stack.purposes.filter((purposeId) =>
			otherPurposeIds.has(purposeId),
		);
		if (coveredPurposeIds.length >= 2) {
			stackScores.push({
				name: stack.name,
				coveredPurposeIds,
				score: coveredPurposeIds.length,
			});
		}
	}

	stackScores.sort((left, right) => right.score - left.score);

	const selectedStacks: string[] = [];
	const assignedPurposeIds = new Set<number>();
	for (const { name, coveredPurposeIds } of stackScores) {
		const unassigned = coveredPurposeIds.filter(
			(purposeId) => !assignedPurposeIds.has(purposeId),
		);
		if (unassigned.length >= 2) {
			selectedStacks.push(name);
			for (const purposeId of unassigned) {
				assignedPurposeIds.add(purposeId);
			}
		}
	}

	const uncoveredPurposes = otherPurposes.filter(
		(purpose) => !assignedPurposeIds.has(purpose.id),
	);

	const specialFeatures = Object.entries(gvlData.specialFeatures || {})
		.filter(([id]) =>
			Object.values(gvlData.vendors).some((vendor) =>
				vendor.specialFeatures?.includes(Number(id)),
			),
		)
		.map(([, feature]) => feature.name);

	const items: string[] = [];
	if (standalonePurpose) {
		items.push(standalonePurpose.name);
	}
	for (const stackName of selectedStacks) {
		items.push(stackName);
	}
	for (const purpose of uncoveredPurposes) {
		items.push(purpose.name);
	}
	for (const featureName of specialFeatures) {
		items.push(featureName);
	}

	return {
		vendorCount,
		displayItems: items.slice(0, MAX_DISPLAY_ITEMS),
		remainingCount: Math.max(0, items.length - MAX_DISPLAY_ITEMS),
		isReady: true,
	};
}

const bannerSummary = computed(() => {
	if (!gvl.value) {
		return {
			isReady: false,
			vendorCount: 0,
			displayItems: [] as string[],
			remainingCount: 0,
		};
	}

	return resolveBannerSummary(gvl.value, customVendors.value);
});

function buildAcceptAllIab(
	gvlData: GlobalVendorList,
	vendors: NonIABVendor[],
): ConsentIabSelection {
	const purposeConsents: Record<number, boolean> = {};
	const purposeLegitimateInterests: Record<number, boolean> = {};
	for (const purposeId of Object.keys(gvlData.purposes)) {
		purposeConsents[Number(purposeId)] = true;
		purposeLegitimateInterests[Number(purposeId)] = true;
	}

	const vendorConsents: Record<string, boolean> = {};
	const vendorLegitimateInterests: Record<string, boolean> = {};
	for (const [vendorId, vendor] of Object.entries(gvlData.vendors)) {
		const id = String(vendorId);
		if (vendor.purposes && vendor.purposes.length > 0) {
			vendorConsents[id] = true;
		}
		if (vendor.legIntPurposes && vendor.legIntPurposes.length > 0) {
			vendorLegitimateInterests[id] = true;
		}
	}
	for (const vendor of vendors) {
		const id = String(vendor.id);
		if (vendor.purposes && vendor.purposes.length > 0) {
			vendorConsents[id] = true;
		}
		if (vendor.legIntPurposes && vendor.legIntPurposes.length > 0) {
			vendorLegitimateInterests[id] = true;
		}
	}

	const specialFeatureOptIns: Record<number, boolean> = {};
	for (const featureId of Object.keys(gvlData.specialFeatures ?? {})) {
		specialFeatureOptIns[Number(featureId)] = true;
	}

	return {
		purposeConsents,
		purposeLegitimateInterests,
		vendorConsents,
		vendorLegitimateInterests,
		specialFeatureOptIns,
		preferenceCenterTab: iabSelection.value.preferenceCenterTab,
	};
}

function buildRejectAllIab(
	gvlData: GlobalVendorList,
	vendors: NonIABVendor[],
): ConsentIabSelection {
	const purposeConsents: Record<number, boolean> = { 1: true };
	const purposeLegitimateInterests: Record<number, boolean> = {};
	for (const purposeId of Object.keys(gvlData.purposes)) {
		if (Number(purposeId) !== 1) {
			purposeConsents[Number(purposeId)] = false;
			purposeLegitimateInterests[Number(purposeId)] = false;
		}
	}

	const vendorConsents: Record<string, boolean> = {};
	const vendorLegitimateInterests: Record<string, boolean> = {};
	for (const [vendorId, vendor] of Object.entries(gvlData.vendors)) {
		const id = String(vendorId);
		if (vendor.purposes && vendor.purposes.length > 0) {
			vendorConsents[id] = false;
		}
		if (vendor.legIntPurposes && vendor.legIntPurposes.length > 0) {
			vendorLegitimateInterests[id] = false;
		}
	}
	for (const vendor of vendors) {
		const id = String(vendor.id);
		if (vendor.purposes && vendor.purposes.length > 0) {
			vendorConsents[id] = false;
		}
		if (vendor.legIntPurposes && vendor.legIntPurposes.length > 0) {
			vendorLegitimateInterests[id] = false;
		}
	}

	const specialFeatureOptIns: Record<number, boolean> = {};
	for (const featureId of Object.keys(gvlData.specialFeatures ?? {})) {
		specialFeatureOptIns[Number(featureId)] = false;
	}

	return {
		purposeConsents,
		purposeLegitimateInterests,
		vendorConsents,
		vendorLegitimateInterests,
		specialFeatureOptIns,
		preferenceCenterTab: iabSelection.value.preferenceCenterTab,
	};
}

const descriptionText = computed(() =>
	(iabT.value?.banner?.description ?? '').replace(
		'{partnerCount}',
		String(bannerSummary.value.vendorCount),
	),
);

const partnersLinkText = computed(() =>
	(iabT.value?.banner?.partnersLink ?? '').replace(
		'{count}',
		String(bannerSummary.value.vendorCount),
	),
);

const descriptionParts = computed(() => {
	const text = descriptionText.value;
	const link = partnersLinkText.value;
	if (!link || !text.includes(link)) {
		return { before: text, after: '' };
	}

	const [before, after] = text.split(link);
	return { before: before ?? text, after: after ?? '' };
});

function isPrimary(button: 'reject' | 'accept' | 'customize') {
	return button === props.primaryButton;
}

function rejectAll() {
	const gvlData = gvl.value;
	if (!gvlData) {
		return;
	}

	iabSelection.value = buildRejectAllIab(gvlData, customVendors.value);
	activeUI.value = null;
}

function acceptAll() {
	const gvlData = gvl.value;
	if (!gvlData) {
		return;
	}

	iabSelection.value = buildAcceptAllIab(gvlData, customVendors.value);
	activeUI.value = null;
}

function openDialog() {
	iabSelection.value.preferenceCenterTab = 'purposes';
	activeUI.value = 'manager';
}

function openVendors() {
	iabSelection.value.preferenceCenterTab = 'vendors';
	activeUI.value = 'manager';
}

const scrollLock = computed(
	() => initValue.value?.policy?.ui?.banner?.scrollLock ?? true,
);

useConsentScrollLock(
	computed(() => Boolean(isOpen.value && scrollLock.value)),
);

const shouldTrapFocus = computed(
	() => Boolean(isOpen.value && (toValue(config).trapFocus ?? true)),
);
</script>

<template>
	<Teleport to="body">
		<Transition
			:disabled="disableAnimation"
			:enter-from-class="bannerStyles.overlayHidden"
			:enter-active-class="bannerStyles.overlayVisible"
			:enter-to-class="bannerStyles.overlayVisible"
			:leave-from-class="bannerStyles.overlayVisible"
			:leave-active-class="bannerStyles.overlayHidden"
			:leave-to-class="bannerStyles.overlayHidden"
		>
			<div
				v-if="showBanner && scrollLock"
				v-bind="config.components?.['iab-banner']?.overlay"
				data-testid="iab-consent-banner-overlay"
				:class="bannerStyles.overlay"
			/>
		</Transition>
		<Transition
			:disabled="disableAnimation"
			:enter-from-class="bannerStyles.bannerHidden"
			:enter-active-class="bannerStyles.bannerVisible"
			:enter-to-class="bannerStyles.bannerVisible"
			:leave-from-class="bannerStyles.bannerVisible"
			:leave-active-class="bannerStyles.bannerHidden"
			:leave-to-class="bannerStyles.bannerHidden"
		>
			<div
				v-if="showBanner"
				v-bind="config.components?.['iab-banner']?.root"
				data-testid="iab-consent-banner-root"
				:class="bannerStyles.root"
			>
			<div :class="bannerStyles.cardShell">
				<ConsentTag v-if="!config.iabBannerHideBranding" context="iab-banner" />
				<FocusScope :trapped="shouldTrapFocus" :loop="shouldTrapFocus">
					<div
						v-bind="config.components?.['iab-banner']?.card"
						data-testid="iab-consent-banner-card"
						:class="bannerStyles.card"
						:role="shouldTrapFocus ? 'dialog' : undefined"
						:aria-modal="shouldTrapFocus ? 'true' : undefined"
						:aria-label="iabT?.banner?.title"
						tabindex="0"
					>
					<div
						v-bind="config.components?.['iab-banner']?.header"
						data-testid="iab-consent-banner-header"
						:class="bannerStyles.header"
					>
						<h2 v-bind="config.components?.['iab-banner']?.title" :class="bannerStyles.title">
							{{ iabT?.banner?.title }}
						</h2>
						<p :class="bannerStyles.description">
							{{ descriptionParts.before }}
							<button
								type="button"
								:class="bannerStyles.partnersLink"
								data-testid="iab-consent-banner-partners-link"
								@click="openVendors"
							>
								{{ partnersLinkText }}
							</button>
							{{ descriptionParts.after }}
						</p>
						<ul :class="bannerStyles.purposeList">
							<li
								v-for="(name, index) in bannerSummary.displayItems"
								:key="`${name}-${index}`"
							>
								{{ name }}
							</li>
							<li
								v-if="bannerSummary.remainingCount > 0"
								:class="bannerStyles.purposeMore"
							>
								{{
									(iabT?.banner?.andMore ?? '').replace(
										'{count}',
										String(bannerSummary.remainingCount),
									)
								}}
							</li>
						</ul>
						<p :class="bannerStyles.legitimateInterestNotice">
							{{ iabT?.banner?.legitimateInterestNotice }}
							{{ iabT?.banner?.scopeServiceSpecific }}
						</p>
					</div>
					<div
						v-bind="config.components?.['iab-banner']?.footer"
						data-testid="iab-consent-banner-footer"
						:class="bannerStyles.footer"
					>
						<div :class="bannerStyles.footerButtonGroup">
							<ConsentButton
								:variant="isPrimary('reject') ? 'primary' : 'neutral'"
								mode="stroke"
								:class="bannerStyles.rejectButton"
								data-testid="iab-consent-banner-reject-button"
								@click="rejectAll"
							>
								{{ iabT?.common?.rejectAll }}
							</ConsentButton>
							<ConsentButton
								:variant="isPrimary('accept') ? 'primary' : 'neutral'"
								:mode="isPrimary('accept') ? 'filled' : 'stroke'"
								:class="bannerStyles.acceptButton"
								data-testid="iab-consent-banner-accept-button"
								@click="acceptAll"
							>
								{{ iabT?.common?.acceptAll }}
							</ConsentButton>
						</div>
						<div :class="bannerStyles.footerSpacer" />
						<ConsentButton
							:variant="isPrimary('customize') ? 'primary' : 'neutral'"
							:mode="isPrimary('customize') ? 'filled' : 'stroke'"
							:class="bannerStyles.customizeButton"
							data-testid="iab-consent-banner-customize-button"
							@click="openDialog"
						>
							{{ iabT?.common?.customize }}
						</ConsentButton>
					</div>
					</div>
				</FocusScope>
			</div>
			</div>
		</Transition>
	</Teleport>
</template>

// packages/svelte/src/lib/components/iab-consent-banner.svelte
<script lang="ts">
import styles from '@c15t/ui/styles/components/iab-consent-banner.module.js';
import { getTextDirection } from '@c15t/ui/utils';
import type { Model } from 'c15t';
import { focusTrap } from '../actions/focus-trap';
import { portal } from '../actions/portal';
import { scrollLock } from '../actions/scroll-lock';
import {
	getConsentContext,
	getThemeContext,
	setTrackingContext,
} from '../context.svelte';
import { getIABTranslations } from '../iab-translations';
import { getIABBannerDisplayItems } from '../iab-types';
import { useBannerVisibility } from '../use-banner-visibility.svelte';
import { resolveComponentStyles } from '../utils';
import Branding from './branding.svelte';
import Overlay from './overlay.svelte';

let {
	noStyle: localNoStyle,
	disableAnimation: localDisableAnimation,
	scrollLock: localScrollLock = true,
	trapFocus: localTrapFocus = true,
	hideBranding = false,
	primaryButton = 'customize' as 'reject' | 'accept' | 'customize',
	models = ['iab'] as Model[],
	uiSource = 'iab_banner',
	class: className,
}: {
	noStyle?: boolean;
	disableAnimation?: boolean;
	scrollLock?: boolean;
	trapFocus?: boolean;
	hideBranding?: boolean;
	primaryButton?: 'reject' | 'accept' | 'customize';
	models?: Model[];
	uiSource?: string;
	class?: string;
} = $props();

const consent = getConsentContext();
const theme = getThemeContext();
setTrackingContext({
	get uiSource() {
		return uiSource;
	},
});

const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);
const disableAnimation = $derived(
	localDisableAnimation ?? theme.disableAnimation ?? false
);
const shouldTrapFocus = $derived(localTrapFocus ?? theme.trapFocus ?? true);
const shouldScrollLock = $derived(localScrollLock ?? theme.scrollLock ?? false);

// IAB state
const iabState = $derived(consent.state.iab);

// Translations
const iabT = $derived(getIABTranslations(consent.state.translationConfig));
const textDirection = $derived(
	getTextDirection(consent.state.translationConfig?.defaultLanguage)
);

// Visibility logic
const shouldShowBanner = $derived(
	consent.state.activeUI === 'banner' &&
		models.includes(consent.state.model) &&
		iabState?.config.enabled === true
);

const visibility = useBannerVisibility(
	() => shouldShowBanner,
	() => disableAnimation
);

// Vendor count from GVL + custom vendors
const vendorCount = $derived.by(() => {
	if (!iabState?.gvl) return 0;
	const gvlVendorCount = Object.keys(iabState.gvl.vendors).length;
	const customVendorCount = iabState.nonIABVendors?.length ?? 0;
	return gvlVendorCount + customVendorCount;
});

// Display items: stacks + purposes + special features (max 5)
const displayItems = $derived.by(() => {
	if (!iabState?.gvl) {
		return { displayed: [] as string[], remainingCount: 0, isReady: false };
	}
	const result = getIABBannerDisplayItems(iabState.gvl);
	return { ...result, isReady: true };
});

// Handlers
function handleAcceptAll() {
	iabState?.acceptAll();
	iabState?.save();
	consent.state.setActiveUI('none');
}

function handleRejectAll() {
	iabState?.rejectAll();
	iabState?.save();
	consent.state.setActiveUI('none');
}

function handleCustomize() {
	iabState?.setPreferenceCenterTab('purposes');
	consent.state.setActiveUI('dialog');
}

function handleViewVendors() {
	iabState?.setPreferenceCenterTab('vendors');
	consent.state.setActiveUI('dialog');
}

function isPrimary(button: 'reject' | 'accept' | 'customize'): boolean {
	return button === primaryButton;
}

// Styling
const rootStyle = $derived(
	resolveComponentStyles(
		'iabConsentBanner',
		theme.theme,
		{
			baseClassName: [
				styles.root,
				textDirection === 'ltr' ? styles.bottomLeft : styles.bottomRight,
			],
			className,
			noStyle,
		},
		noStyle
	)
);

const finalClassName = $derived(
	noStyle
		? rootStyle.className || ''
		: `${rootStyle.className || ''} ${visibility.isVisible ? styles.bannerVisible : styles.bannerHidden}`
);

// Resolved texts
const descriptionText = $derived(
	iabT.banner.description.replace('{partnerCount}', String(vendorCount))
);
const partnersLinkText = $derived(
	iabT.banner.partnersLink.replace('{count}', String(vendorCount))
);
const scopeNotice = $derived(iabT.banner.scopeServiceSpecific);

// Split description around partners link
const descriptionParts = $derived(descriptionText.split(partnersLinkText));
</script>

{#if visibility.isMounted && visibility.shouldRender && displayItems.isReady}
	<div use:portal>
		<Overlay visible={visibility.isVisible} />
		<div
			bind:this={visibility.bannerEl}
			class={finalClassName}
			dir={textDirection}
			data-testid="iab-consent-banner-root"
			use:focusTrap={shouldTrapFocus}
			use:scrollLock={shouldScrollLock}
		>
			<div class={noStyle ? '' : styles.cardShell || ''}>
				<Branding
					{hideBranding}
					{noStyle}
					variant="banner-tag"
					themeKey="iabConsentBannerTag"
					data-testid="iab-consent-banner-branding"
				/>
				<div
					class={noStyle ? '' : styles.card}
					data-testid="iab-consent-banner-card"
					role={shouldTrapFocus ? 'dialog' : undefined}
					aria-modal={shouldTrapFocus ? 'true' : undefined}
					aria-label={iabT.banner.title}
				>
					<!-- Header -->
					<div class={noStyle ? '' : styles.header} data-testid="iab-consent-banner-header">
						<h2 class={noStyle ? '' : styles.title}>{iabT.banner.title}</h2>
						<p class={noStyle ? '' : styles.description}>
							{descriptionParts[0]}<button
								type="button"
								class={noStyle ? '' : styles.partnersLink}
								onclick={handleViewVendors}
							>
								{partnersLinkText}
							</button>{descriptionParts[1] ?? ''}
						</p>
						<ul class={noStyle ? '' : styles.purposeList}>
							{#each displayItems.displayed as name (name)}
								<li>{name}</li>
							{/each}
							{#if displayItems.remainingCount > 0}
								<li class={noStyle ? '' : styles.purposeMore}>
									{iabT.banner.andMore.replace('{count}', String(displayItems.remainingCount))}
								</li>
							{/if}
						</ul>
						<p class={noStyle ? '' : styles.legitimateInterestNotice}>
							{iabT.banner.legitimateInterestNotice}
							{scopeNotice}
						</p>
					</div>

					<!-- Footer with buttons -->
					<div class={noStyle ? '' : styles.footer} data-testid="iab-consent-banner-footer">
						<div class={noStyle ? '' : styles.footerButtonGroup}>
							<button
								type="button"
								class={noStyle
									? ''
									: `${styles.rejectButton || ''} ${isPrimary('reject') ? styles.primaryButton || '' : ''}`}
								onclick={handleRejectAll}
								data-testid="iab-consent-banner-reject-button"
							>
								{iabT.common.rejectAll}
							</button>
							<button
								type="button"
								class={noStyle
									? ''
									: `${styles.acceptButton || ''} ${isPrimary('accept') ? styles.primaryButton || '' : ''}`}
								onclick={handleAcceptAll}
								data-testid="iab-consent-banner-accept-button"
							>
								{iabT.common.acceptAll}
							</button>
						</div>
						<div class={noStyle ? '' : styles.footerSpacer}></div>
						<button
							type="button"
							class={noStyle
								? ''
								: `${styles.customizeButton || ''} ${isPrimary('customize') ? styles.primaryButton || '' : ''}`}
							onclick={handleCustomize}
							data-testid="iab-consent-banner-customize-button"
						>
							{iabT.common.customize}
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
{/if}
