// packages/vue/src/runtime/components/iab-consent-dialog.vue
<script setup lang="ts">
import { computed, ref, toValue, watch } from 'vue';
import { Teleport, Transition } from 'vue';
import { FocusScope } from 'reka-ui';
import type {
	GlobalVendorList,
	NonIABVendor,
} from '@c15t/schema/types';
import dialogStyles from '@c15t/styles/iab-consent-dialog.module.css';
import {
	createDefaultIabSelection,
	useConsentActiveUI,
	useConsentConfig,
	useConsentInit,
	useConsentIabSelection,
	type ConsentIabSelection,
} from '#c15t/composables';
import ConsentButton from './consent-button.vue';
import ConsentTag from './consent-tag.vue';
import IabPurposeItem from './iab-purpose-item.vue';
import IabStackItem from './iab-stack-item.vue';
import type { IabProcessedStack } from './iab-stack-item.vue';
import IabVendorList from './iab-vendor-list.vue';
import type {
	IabProcessedPurpose,
	IabProcessedVendor,
	IabVendorId,
} from './iab-purpose-item.vue';
import ConsentDialogTrigger from './consent-dialog-trigger.vue';
import { useConsentScrollLock } from '../composables/use-consent-scroll-lock';
const STANDALONE_PURPOSE_ID = 1;

const activeUI = useConsentActiveUI();
const config = useConsentConfig();
const init = useConsentInit();
const iabSelection = useConsentIabSelection();

const initValue = computed(() => toValue(init));
const gvl = computed(() => initValue.value?.gvl ?? null);
const customVendors = computed(() => initValue.value?.customVendors ?? []);
const draftIab = ref<ConsentIabSelection>(createDefaultIabSelection());

const isOpen = computed(() => {
	const models = config.value.iabDialogModels;
	const model = initValue.value?.policy?.model;
	const matchesModel =
		!models?.length || (model !== undefined && models.includes(model));
	return (
		activeUI.value === 'manager' &&
		initValue.value?.policy?.model === 'iab' &&
		Boolean(gvl.value) &&
		matchesModel
	);
});
const disableAnimation = computed(() => Boolean(toValue(config).disableAnimation));

const showDialog = computed(() => isOpen.value && Boolean(gvl.value));

const activeTab = ref<'purposes' | 'vendors'>('purposes');
const selectedVendorId = ref<IabVendorId | null>(null);
const specialPurposesExpanded = ref(false);

const iabT = computed(
	() =>
		(toValue(init)?.translations?.translations as { iab?: Record<string, unknown> })
			?.iab as {
			common?: {
				acceptAll?: string;
				rejectAll?: string;
				saveSettings?: string;
				close?: string;
				loading?: string;
			};
			preferenceCenter?: {
				title?: string;
				description?: string;
				tabs?: { purposes?: string; vendors?: string };
				specialPurposes?: { title?: string; tooltip?: string };
				footer?: { consentStorage?: string };
			};
		} | undefined,
);

function mapVendor(
	gvl: GlobalVendorList,
	vendorId: string,
	vendor: GlobalVendorList['vendors'][string],
	purposeId?: number,
): IabProcessedVendor {
	return {
		id: Number(vendorId),
		name: vendor.name,
		usesLegitimateInterest: purposeId
			? (vendor.legIntPurposes?.includes(purposeId) ?? false)
			: false,
		isCustom: false,
	};
}

function mapCustomVendor(
	vendor: NonIABVendor,
	purposeId?: number,
): IabProcessedVendor {
	return {
		id: vendor.id,
		name: vendor.name,
		usesLegitimateInterest: purposeId
			? (vendor.legIntPurposes?.includes(purposeId) ?? false)
			: false,
		isCustom: true,
	};
}

function processGvlData(
	gvl: GlobalVendorList,
	customVendors: NonIABVendor[],
) {
	const processedPurposes: IabProcessedPurpose[] = Object.entries(gvl.purposes)
		.map(([id, purpose]) => {
			const purposeId = Number(id);
			const iabVendors = Object.entries(gvl.vendors)
				.filter(([, vendor]) =>
					vendor.purposes?.includes(purposeId) ||
					vendor.legIntPurposes?.includes(purposeId),
				)
				.map(([vendorId, vendor]) =>
					mapVendor(gvl, vendorId, vendor, purposeId),
				);
			const customForPurpose = customVendors
				.filter(
					(vendor) =>
						vendor.purposes?.includes(purposeId) ||
						vendor.legIntPurposes?.includes(purposeId),
				)
				.map((vendor) => mapCustomVendor(vendor, purposeId));

			return {
				id: purposeId,
				name: purpose.name,
				description: purpose.description,
				illustrations: purpose.illustrations ?? [],
				vendors: [...iabVendors, ...customForPurpose],
			};
		})
		.filter((purpose) => purpose.vendors.length > 0);

	const specialPurposes: IabProcessedPurpose[] = Object.entries(
		gvl.specialPurposes ?? {},
	)
		.map(([id, purpose]) => ({
			id: Number(id),
			name: purpose.name,
			description: purpose.description,
			illustrations: purpose.illustrations ?? [],
			vendors: Object.entries(gvl.vendors)
				.filter(([, vendor]) => vendor.specialPurposes?.includes(Number(id)))
				.map(([vendorId, vendor]) => mapVendor(gvl, vendorId, vendor)),
		}))
		.filter((purpose) => purpose.vendors.length > 0);

	const specialFeatures: IabProcessedPurpose[] = Object.entries(
		gvl.specialFeatures ?? {},
	)
		.map(([id, feature]) => ({
			id: Number(id),
			name: feature.name,
			description: feature.description,
			illustrations: feature.illustrations ?? [],
			vendors: Object.entries(gvl.vendors)
				.filter(([, vendor]) => vendor.specialFeatures?.includes(Number(id)))
				.map(([vendorId, vendor]) => mapVendor(gvl, vendorId, vendor)),
		}))
		.filter((feature) => feature.vendors.length > 0);

	const features: IabProcessedPurpose[] = Object.entries(gvl.features ?? {})
		.map(([id, feature]) => ({
			id: Number(id),
			name: feature.name,
			description: feature.description,
			illustrations: feature.illustrations ?? [],
			vendors: Object.entries(gvl.vendors)
				.filter(([, vendor]) => vendor.features?.includes(Number(id)))
				.map(([vendorId, vendor]) => mapVendor(gvl, vendorId, vendor)),
		}))
		.filter((feature) => feature.vendors.length > 0);

	const standalonePurpose = processedPurposes.find(
		(purpose) => purpose.id === STANDALONE_PURPOSE_ID,
	);
	const otherPurposes = processedPurposes.filter(
		(purpose) => purpose.id !== STANDALONE_PURPOSE_ID,
	);
	const otherPurposeIds = new Set(otherPurposes.map((purpose) => purpose.id));

	const stackScores: Array<{
		stackId: number;
		stack: GlobalVendorList['stacks'][string];
		coveredPurposeIds: number[];
		score: number;
	}> = [];

	for (const [stackIdStr, stack] of Object.entries(gvl.stacks ?? {})) {
		const coveredIds = stack.purposes.filter((purposeId) =>
			otherPurposeIds.has(purposeId),
		);
		if (coveredIds.length >= 2) {
			stackScores.push({
				stackId: Number(stackIdStr),
				stack,
				coveredPurposeIds: coveredIds,
				score: coveredIds.length,
			});
		}
	}

	stackScores.sort((left, right) => right.score - left.score);

	const stacks: IabProcessedStack[] = [];
	const assignedPurposeIds = new Set<number>();

	for (const { stackId, stack, coveredPurposeIds } of stackScores) {
		const unassigned = coveredPurposeIds.filter(
			(purposeId) => !assignedPurposeIds.has(purposeId),
		);
		if (unassigned.length >= 2) {
			stacks.push({
				id: stackId,
				name: stack.name,
				description: stack.description,
				purposes: otherPurposes.filter((purpose) =>
					unassigned.includes(purpose.id),
				),
			});
			for (const purposeId of unassigned) {
				assignedPurposeIds.add(purposeId);
			}
		}
	}

	const uncoveredPurposes = otherPurposes.filter(
		(purpose) => !assignedPurposeIds.has(purpose.id),
	);
	const standalonePurposes = standalonePurpose
		? [standalonePurpose, ...uncoveredPurposes]
		: uncoveredPurposes;

	return {
		purposes: processedPurposes,
		specialPurposes,
		specialFeatures,
		features,
		stacks,
		standalonePurposes,
	};
}

const processed = computed(() => {
	if (!gvl.value) {
		return {
			purposes: [] as IabProcessedPurpose[],
			specialPurposes: [] as IabProcessedPurpose[],
			specialFeatures: [] as IabProcessedPurpose[],
			features: [] as IabProcessedPurpose[],
			stacks: [] as IabProcessedStack[],
			standalonePurposes: [] as IabProcessedPurpose[],
		};
	}

	return processGvlData(gvl.value, customVendors.value);
});

const isLoading = computed(() => !gvl.value);

const totalVendors = computed(() => {
	if (!gvl.value) {
		return 0;
	}

	return Object.keys(gvl.value.vendors).length + customVendors.value.length;
});

const purposeTabCount = computed(
	() =>
		processed.value.purposes.length +
		processed.value.specialPurposes.length +
		processed.value.specialFeatures.length +
		processed.value.features.length,
);

const essentialPartnerCount = computed(
	() =>
		new Set([
			...processed.value.specialPurposes.flatMap((purpose) =>
				purpose.vendors.map((vendor) => vendor.id),
			),
			...processed.value.features.flatMap((feature) =>
				feature.vendors.map((vendor) => vendor.id),
			),
		]).size,
);

function buildAcceptAllIab(
	gvlData: GlobalVendorList,
	vendors: NonIABVendor[],
	tab: ConsentIabSelection['preferenceCenterTab'],
): ConsentIabSelection {
	const purposeConsents: Record<number, boolean> = {};
	const purposeLegitimateInterests: Record<number, boolean> = {};
	for (const purposeId of Object.keys(gvlData.purposes)) {
		purposeConsents[Number(purposeId)] = true;
		purposeLegitimateInterests[Number(purposeId)] = true;
	}

	const vendorConsents: Record<string, boolean> = {};
	const vendorLegitimateInterests: Record<string, boolean> = {};
	for (const [vendorId, vendor] of Object.entries(gvlData.vendors)) {
		const id = String(vendorId);
		if (vendor.purposes && vendor.purposes.length > 0) {
			vendorConsents[id] = true;
		}
		if (vendor.legIntPurposes && vendor.legIntPurposes.length > 0) {
			vendorLegitimateInterests[id] = true;
		}
	}
	for (const vendor of vendors) {
		const id = String(vendor.id);
		if (vendor.purposes && vendor.purposes.length > 0) {
			vendorConsents[id] = true;
		}
		if (vendor.legIntPurposes && vendor.legIntPurposes.length > 0) {
			vendorLegitimateInterests[id] = true;
		}
	}

	const specialFeatureOptIns: Record<number, boolean> = {};
	for (const featureId of Object.keys(gvlData.specialFeatures ?? {})) {
		specialFeatureOptIns[Number(featureId)] = true;
	}

	return {
		purposeConsents,
		purposeLegitimateInterests,
		vendorConsents,
		vendorLegitimateInterests,
		specialFeatureOptIns,
		preferenceCenterTab: tab,
	};
}

function buildRejectAllIab(
	gvlData: GlobalVendorList,
	vendors: NonIABVendor[],
	tab: ConsentIabSelection['preferenceCenterTab'],
): ConsentIabSelection {
	const purposeConsents: Record<number, boolean> = { 1: true };
	const purposeLegitimateInterests: Record<number, boolean> = {};
	for (const purposeId of Object.keys(gvlData.purposes)) {
		if (Number(purposeId) !== 1) {
			purposeConsents[Number(purposeId)] = false;
			purposeLegitimateInterests[Number(purposeId)] = false;
		}
	}

	const vendorConsents: Record<string, boolean> = {};
	const vendorLegitimateInterests: Record<string, boolean> = {};
	for (const [vendorId, vendor] of Object.entries(gvlData.vendors)) {
		const id = String(vendorId);
		if (vendor.purposes && vendor.purposes.length > 0) {
			vendorConsents[id] = false;
		}
		if (vendor.legIntPurposes && vendor.legIntPurposes.length > 0) {
			vendorLegitimateInterests[id] = false;
		}
	}
	for (const vendor of vendors) {
		const id = String(vendor.id);
		if (vendor.purposes && vendor.purposes.length > 0) {
			vendorConsents[id] = false;
		}
		if (vendor.legIntPurposes && vendor.legIntPurposes.length > 0) {
			vendorLegitimateInterests[id] = false;
		}
	}

	const specialFeatureOptIns: Record<number, boolean> = {};
	for (const featureId of Object.keys(gvlData.specialFeatures ?? {})) {
		specialFeatureOptIns[Number(featureId)] = false;
	}

	return {
		purposeConsents,
		purposeLegitimateInterests,
		vendorConsents,
		vendorLegitimateInterests,
		specialFeatureOptIns,
		preferenceCenterTab: tab,
	};
}

function setPurposeConsent(purposeId: number, value: boolean) {
	draftIab.value.purposeConsents = {
		...draftIab.value.purposeConsents,
		[purposeId]: value,
	};
}

function setPurposeLegitimateInterest(purposeId: number, value: boolean) {
	draftIab.value.purposeLegitimateInterests = {
		...draftIab.value.purposeLegitimateInterests,
		[purposeId]: value,
	};
}

function setVendorConsent(vendorId: IabVendorId, value: boolean) {
	draftIab.value.vendorConsents = {
		...draftIab.value.vendorConsents,
		[String(vendorId)]: value,
	};
}

function setSpecialFeatureOptIn(featureId: number, value: boolean) {
	draftIab.value.specialFeatureOptIns = {
		...draftIab.value.specialFeatureOptIns,
		[featureId]: value,
	};
}

function syncDraftFromSelection() {
	draftIab.value = structuredClone(iabSelection.value);
}

watch(
	isOpen,
	(open) => {
		if (!open) {
			return;
		}

		syncDraftFromSelection();
		activeTab.value = draftIab.value.preferenceCenterTab;
	},
	{ immediate: true },
);

watch(
	() => iabSelection.value.preferenceCenterTab,
	(tab) => {
		if (isOpen.value) {
			activeTab.value = tab;
			draftIab.value.preferenceCenterTab = tab;
		}
	},
);

function handleTabChange(tab: 'purposes' | 'vendors') {
	activeTab.value = tab;
	draftIab.value.preferenceCenterTab = tab;
	iabSelection.value.preferenceCenterTab = tab;
}

function closeDialog() {
	activeUI.value = null;
}

function rejectAll() {
	const gvlData = gvl.value;
	if (!gvlData) {
		return;
	}

	iabSelection.value = buildRejectAllIab(
		gvlData,
		customVendors.value,
		activeTab.value,
	);
	activeUI.value = null;
}

function acceptAll() {
	const gvlData = gvl.value;
	if (!gvlData) {
		return;
	}

	iabSelection.value = buildAcceptAllIab(
		gvlData,
		customVendors.value,
		activeTab.value,
	);
	activeUI.value = null;
}

function savePreferences() {
	iabSelection.value = {
		...structuredClone(draftIab.value),
		preferenceCenterTab: activeTab.value,
	};
	activeUI.value = null;
}

function handleVendorClick(vendorId: IabVendorId) {
	selectedVendorId.value = vendorId;
	handleTabChange('vendors');
}

const scrollLock = computed(
	() => initValue.value?.policy?.ui?.dialog?.scrollLock ?? true,
);

useConsentScrollLock(
	computed(() => Boolean(isOpen.value && scrollLock.value)),
);

const shouldTrapFocus = computed(
	() => Boolean(isOpen.value && (toValue(config).trapFocus ?? true)),
);
</script>

<template>
	<ConsentDialogTrigger v-if="config.iabDialogShowTrigger" />
	<Teleport to="body">
		<Transition
			:disabled="disableAnimation"
			:enter-from-class="dialogStyles.overlayHidden"
			:enter-active-class="dialogStyles.overlayVisible"
			:enter-to-class="dialogStyles.overlayVisible"
			:leave-from-class="dialogStyles.overlayVisible"
			:leave-active-class="dialogStyles.overlayHidden"
			:leave-to-class="dialogStyles.overlayHidden"
		>
			<div
				v-if="showDialog && scrollLock"
				v-bind="config.components?.['iab-dialog']?.overlay"
				data-testid="iab-consent-dialog-overlay"
				:class="dialogStyles.overlay"
			/>
		</Transition>
		<Transition
			:disabled="disableAnimation"
			:enter-from-class="dialogStyles.dialogHidden"
			:enter-active-class="dialogStyles.dialogVisible"
			:enter-to-class="dialogStyles.dialogVisible"
			:leave-from-class="dialogStyles.dialogVisible"
			:leave-active-class="dialogStyles.dialogHidden"
			:leave-to-class="dialogStyles.dialogHidden"
		>
			<div
				v-if="showDialog"
				v-bind="config.components?.['iab-dialog']?.root"
				data-testid="iab-consent-dialog-root"
				:class="dialogStyles.root"
			>
			<FocusScope :trapped="shouldTrapFocus" :loop="shouldTrapFocus">
				<Transition
					:disabled="disableAnimation"
					:enter-from-class="dialogStyles.contentHidden"
					:enter-active-class="dialogStyles.contentVisible"
					:enter-to-class="dialogStyles.contentVisible"
					:leave-from-class="dialogStyles.contentVisible"
					:leave-active-class="dialogStyles.contentHidden"
					:leave-to-class="dialogStyles.contentHidden"
				>
					<div
						v-if="showDialog"
						v-bind="config.components?.['iab-dialog']?.card"
						data-testid="iab-consent-dialog-card"
						:class="dialogStyles.card"
					:role="shouldTrapFocus ? 'dialog' : undefined"
					:aria-modal="shouldTrapFocus ? 'true' : undefined"
					:aria-label="iabT?.preferenceCenter?.title"
					tabindex="0"
				>
				<div v-bind="config.components?.['iab-dialog']?.header" :class="dialogStyles.header">
					<div :class="dialogStyles.headerContent">
						<h2 v-bind="config.components?.['iab-dialog']?.title" :class="dialogStyles.title">
							{{ iabT?.preferenceCenter?.title }}
						</h2>
						<p :class="dialogStyles.description">
							{{ iabT?.preferenceCenter?.description }}
						</p>
					</div>
					<button
						type="button"
						:class="dialogStyles.closeButton"
						:aria-label="iabT?.common?.close"
						data-testid="iab-consent-dialog-close"
						@click="closeDialog"
					>
						<svg
							style="width: 1rem; height: 1rem"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
						>
							<line x1="18" y1="6" x2="6" y2="18" />
							<line x1="6" y1="6" x2="18" y2="18" />
						</svg>
					</button>
				</div>

				<div :class="dialogStyles.body">
					<div v-bind="config.components?.['iab-dialog']?.tabs" :class="dialogStyles.tabsContainer">
						<div :class="dialogStyles.tabsList" role="tablist">
							<button
								type="button"
								:class="dialogStyles.tabButton"
								role="tab"
								:aria-selected="activeTab === 'purposes'"
								:data-state="activeTab === 'purposes' ? 'active' : 'inactive'"
								@click="handleTabChange('purposes')"
							>
								{{ iabT?.preferenceCenter?.tabs?.purposes }}
								<span v-if="!isLoading"> ({{ purposeTabCount }})</span>
							</button>
							<button
								type="button"
								:class="dialogStyles.tabButton"
								role="tab"
								:aria-selected="activeTab === 'vendors'"
								:data-state="activeTab === 'vendors' ? 'active' : 'inactive'"
								@click="handleTabChange('vendors')"
							>
								{{ iabT?.preferenceCenter?.tabs?.vendors }}
								<span v-if="!isLoading"> ({{ totalVendors }})</span>
							</button>
							<div
								aria-hidden="true"
								:class="dialogStyles.tabIndicator"
								:data-active-tab="activeTab"
							/>
						</div>
					</div>

					<div v-bind="config.components?.['iab-dialog']?.content" :class="dialogStyles.content">
						<div v-if="isLoading" :class="dialogStyles.loadingContainer">
							<div :class="dialogStyles.loadingSpinner" />
							<p :class="dialogStyles.loadingText">
								{{ iabT?.common?.loading }}
							</p>
						</div>
						<template v-else>
							<div
								v-show="activeTab === 'purposes'"
								:class="dialogStyles.tabPanel"
								role="tabpanel"
							>
								<IabPurposeItem
									v-for="purpose in processed.standalonePurposes"
									:key="purpose.id"
									:purpose="purpose"
									:is-enabled="draftIab.purposeConsents[purpose.id] ?? false"
									:vendor-consents="draftIab.vendorConsents"
									:vendor-legitimate-interests="draftIab.vendorLegitimateInterests"
									:purpose-legitimate-interests="draftIab.purposeLegitimateInterests"
									@toggle="(value) => setPurposeConsent(purpose.id, value)"
									@vendor-toggle="
										(vendorId, value) => setVendorConsent(vendorId, value)
									"
									@vendor-click="handleVendorClick"
									@purpose-legitimate-interest-toggle="
										(value) =>
											setPurposeLegitimateInterest(purpose.id, value)
									"
								/>

								<IabStackItem
									v-for="stack in processed.stacks"
									:key="stack.id"
									:stack="stack"
									:consents="draftIab.purposeConsents"
									:vendor-consents="draftIab.vendorConsents"
									:vendor-legitimate-interests="draftIab.vendorLegitimateInterests"
									:purpose-legitimate-interests="draftIab.purposeLegitimateInterests"
									@toggle="
										(purposeId, value) => setPurposeConsent(purposeId, value)
									"
									@vendor-toggle="
										(vendorId, value) => setVendorConsent(vendorId, value)
									"
									@vendor-click="handleVendorClick"
									@purpose-legitimate-interest-toggle="
										(purposeId, value) =>
											setPurposeLegitimateInterest(purposeId, value)
									"
								/>

								<IabPurposeItem
									v-for="feature in processed.specialFeatures"
									:key="`feature-${feature.id}`"
									:purpose="feature"
									:is-enabled="draftIab.specialFeatureOptIns[feature.id] ?? false"
									:vendor-consents="draftIab.vendorConsents"
									:vendor-legitimate-interests="draftIab.vendorLegitimateInterests"
									@toggle="
										(value) => setSpecialFeatureOptIn(feature.id, value)
									"
									@vendor-toggle="
										(vendorId, value) => setVendorConsent(vendorId, value)
									"
									@vendor-click="handleVendorClick"
								/>

								<div
									v-if="
										processed.specialPurposes.length > 0 ||
										processed.features.length > 0
									"
									:class="dialogStyles.specialPurposesSection"
								>
									<div :class="dialogStyles.specialPurposesHeader">
										<button
											type="button"
											:class="dialogStyles.purposeTrigger"
											:aria-expanded="specialPurposesExpanded"
											@click="
												specialPurposesExpanded = !specialPurposesExpanded
											"
										>
											<svg
												:class="dialogStyles.purposeArrow"
												viewBox="0 0 24 24"
												fill="none"
												stroke="currentColor"
												stroke-width="2"
											>
												<path
													v-if="specialPurposesExpanded"
													d="M19 9l-7 7-7-7"
												/>
												<path v-else d="M9 5l7 7-7 7" />
											</svg>
											<div :class="dialogStyles.purposeInfo">
												<h3 :class="dialogStyles.specialPurposesTitle">
													{{
														iabT?.preferenceCenter?.specialPurposes?.title
													}}
													<svg
														:class="dialogStyles.lockIcon"
														viewBox="0 0 24 24"
														fill="none"
														stroke="currentColor"
														stroke-width="2"
													>
														<rect
															x="3"
															y="11"
															width="18"
															height="11"
															rx="2"
															ry="2"
														/>
														<path d="M7 11V7a5 5 0 0 1 10 0v4" />
													</svg>
												</h3>
												<p :class="dialogStyles.purposeMeta">
													{{ essentialPartnerCount }}
													partners
												</p>
											</div>
										</button>
										<svg
											:class="dialogStyles.infoIcon"
											viewBox="0 0 24 24"
											fill="none"
											stroke="currentColor"
											stroke-width="2"
											:aria-label="
												iabT?.preferenceCenter?.specialPurposes?.tooltip
											"
										>
											<circle cx="12" cy="12" r="10" />
											<line x1="12" y1="16" x2="12" y2="12" />
											<line x1="12" y1="8" x2="12.01" y2="8" />
										</svg>
									</div>

									<div v-if="specialPurposesExpanded" style="padding: 0.75rem">
										<IabPurposeItem
											v-for="purpose in processed.specialPurposes"
											:key="`special-${purpose.id}`"
											:purpose="purpose"
											:is-enabled="true"
											is-locked
											:vendor-consents="draftIab.vendorConsents"
											@vendor-toggle="
												(vendorId, value) => setVendorConsent(vendorId, value)
											"
											@vendor-click="handleVendorClick"
										/>
										<IabPurposeItem
											v-for="feature in processed.features"
											:key="`locked-feature-${feature.id}`"
											:purpose="feature"
											:is-enabled="true"
											is-locked
											:vendor-consents="draftIab.vendorConsents"
											@vendor-toggle="
												(vendorId, value) => setVendorConsent(vendorId, value)
											"
											@vendor-click="handleVendorClick"
										/>
									</div>
								</div>

								<div :class="dialogStyles.consentNotice">
									<p :class="dialogStyles.consentNoticeText">
										{{ iabT?.preferenceCenter?.footer?.consentStorage }}
									</p>
								</div>
							</div>

							<div
								v-show="activeTab === 'vendors'"
								:class="dialogStyles.tabPanel"
								role="tabpanel"
							>
								<IabVendorList
									:vendor-data="gvl"
									:purposes="processed.purposes"
									:vendor-consents="draftIab.vendorConsents"
									:selected-vendor-id="selectedVendorId"
									:custom-vendors="customVendors"
									:vendor-legitimate-interests="draftIab.vendorLegitimateInterests"
									@vendor-toggle="
										(vendorId, value) => setVendorConsent(vendorId, value)
									"
									@clear-selection="selectedVendorId = null"
								/>
							</div>
						</template>
					</div>
				</div>

				<div v-bind="config.components?.['iab-dialog']?.footer" :class="dialogStyles.footer">
					<div :class="dialogStyles.footerButtons">
						<ConsentButton
							variant="neutral"
							mode="stroke"
							:disabled="isLoading"
							data-testid="iab-consent-dialog-reject-button"
							@click="rejectAll"
						>
							{{ iabT?.common?.rejectAll }}
						</ConsentButton>
						<ConsentButton
							variant="neutral"
							mode="stroke"
							:disabled="isLoading"
							data-testid="iab-consent-dialog-accept-button"
							@click="acceptAll"
						>
							{{ iabT?.common?.acceptAll }}
						</ConsentButton>
					</div>
					<div :class="dialogStyles.footerSpacer" />
					<ConsentButton
						variant="primary"
						mode="filled"
						:disabled="isLoading"
						data-testid="iab-consent-dialog-save-button"
						@click="savePreferences"
					>
						{{ iabT?.common?.saveSettings }}
					</ConsentButton>
				</div>

				<ConsentTag v-if="!config.iabDialogHideBranding" context="iab-dialog" />
					</div>
				</Transition>
			</FocusScope>
			</div>
		</Transition>
	</Teleport>
</template>

// packages/svelte/src/lib/components/iab-consent-dialog.svelte
<script lang="ts">
import styles from '@c15t/ui/styles/components/iab-consent-dialog.module.js';
import { getTextDirection } from '@c15t/ui/utils';
import type { Model } from 'c15t';
import { getConsentContext, getThemeContext } from '../context.svelte';
import { getIABTranslations } from '../iab-translations';
import { processGVLData, type VendorId } from '../iab-types';
import { Collapsible, Dialog, Portal, Tabs } from '../primitives';
import Branding from './branding.svelte';
import IABPurposeItem from './iab-purpose-item.svelte';
import IABStackItem from './iab-stack-item.svelte';
import IABVendorList from './iab-vendor-list.svelte';
import ChevronRightIcon from './icons/chevron-right-icon.svelte';
import CloseIcon from './icons/close-icon.svelte';
import InfoIcon from './icons/info-icon.svelte';
import LockIcon from './icons/lock-icon.svelte';

let {
	open: openProp,
	noStyle: localNoStyle,
	hideBranding,
	models = ['iab'] as Model[],
	class: className,
}: {
	open?: boolean;
	noStyle?: boolean;
	hideBranding?: boolean;
	models?: Model[];
	class?: string;
} = $props();

const consent = getConsentContext();
const theme = getThemeContext();

const noStyle = $derived(localNoStyle ?? theme.noStyle ?? false);

// IAB state
const iabState = $derived(consent.state.iab);

// Translations
const iabT = $derived(getIABTranslations(consent.state.translationConfig));
const textDirection = $derived(
	getTextDirection(consent.state.translationConfig?.defaultLanguage)
);

// Open state
const isOpen = $derived(
	models.includes(consent.state.model) &&
		(openProp ?? consent.state.activeUI === 'dialog') &&
		iabState?.config.enabled === true
);

// Tab state
let activeTab = $state<string | null>('purposes');
let selectedVendorId = $state<VendorId | null>(null);
let specialPurposesExpanded = $state(false);

// Sync tab from iabState when dialog opens
$effect(() => {
	if (isOpen && iabState?.preferenceCenterTab) {
		activeTab = iabState.preferenceCenterTab;
	}
});

// Process GVL data
const gvlData = $derived.by(() => {
	if (!iabState?.gvl) return null;
	return processGVLData(iabState.gvl, iabState.nonIABVendors || []);
});

// Total vendor count
const totalVendors = $derived.by(() => {
	if (!iabState?.gvl) return 0;
	const gvlVendorCount = Object.keys(iabState.gvl.vendors).length;
	const customVendorCount = iabState.nonIABVendors?.length ?? 0;
	return gvlVendorCount + customVendorCount;
});

const isLoading = $derived(iabState?.isLoadingGVL || !iabState?.gvl);

// Partner count for special purposes + features section
const specialSectionPartnerCount = $derived.by(() => {
	if (!gvlData) return 0;
	return new Set([
		...gvlData.specialPurposes.flatMap((sp) => sp.vendors.map((v) => v.id)),
		...gvlData.features.flatMap((f) => f.vendors.map((v) => v.id)),
	]).size;
});

// Handlers
function handleOpenChange(details: { open: boolean }) {
	if (!details.open) {
		consent.state.setActiveUI('none');
	}
}

function handleTabChange(details: { value: string | null }) {
	if (details.value === 'purposes' || details.value === 'vendors') {
		activeTab = details.value;
		iabState?.setPreferenceCenterTab(details.value);
	}
}

function handlePurposeToggle(purposeId: number, value: boolean) {
	iabState?.setPurposeConsent(purposeId, value);
}

function handleSpecialFeatureToggle(featureId: number, value: boolean) {
	iabState?.setSpecialFeatureOptIn(featureId, value);
}

function handleVendorToggle(vendorId: VendorId, value: boolean) {
	iabState?.setVendorConsent(vendorId, value);
}

function handleVendorLegitimateInterestToggle(
	vendorId: VendorId,
	value: boolean
) {
	iabState?.setVendorLegitimateInterest(vendorId, value);
}

function handlePurposeLegitimateInterestToggle(
	purposeId: number,
	value: boolean
) {
	iabState?.setPurposeLegitimateInterest(purposeId, value);
}

function handleAcceptAll() {
	iabState?.acceptAll();
	iabState?.save();
	consent.state.setActiveUI('none');
}

function handleRejectAll() {
	iabState?.rejectAll();
	iabState?.save();
	consent.state.setActiveUI('none');
}

function handleSave() {
	iabState?.save();
	consent.state.setActiveUI('none');
}

function handleVendorClick(vendorId: VendorId) {
	selectedVendorId = vendorId;
	activeTab = 'vendors';
	iabState?.setPreferenceCenterTab('vendors');
}
</script>

<Dialog.Root
	open={isOpen}
	onOpenChange={handleOpenChange}
	closeOnInteractOutside={false}
	closeOnEscape={true}
	trapFocus={true}
	preventScroll={true}
	lazyMount
	unmountOnExit
>
	<Portal>
		<Dialog.Backdrop
			class={noStyle ? '' : styles.overlay || ''}
			data-testid="consent-dialog-overlay"
		/>
		<Dialog.Positioner
			class={noStyle
				? ''
				: `${styles.root || ''} ${isOpen ? styles.dialogVisible || '' : styles.dialogHidden || ''}`}
			data-testid="iab-consent-dialog-root"
		>
			<Dialog.Content
				class={noStyle
					? className || ''
					: `${styles.card || ''} ${className || ''} ${isOpen ? styles.contentVisible || '' : styles.contentHidden || ''}`}
				dir={textDirection}
				data-testid="iab-consent-dialog-card"
			>
				<!-- Header -->
				<div class={noStyle ? '' : styles.header || ''}>
					<div class={noStyle ? '' : styles.headerContent || ''}>
						<Dialog.Title class={noStyle ? '' : styles.title || ''}>
							{iabT.preferenceCenter.title}
						</Dialog.Title>
						<Dialog.Description class={noStyle ? '' : styles.description || ''}>
							{iabT.preferenceCenter.description}
						</Dialog.Description>
					</div>
					<Dialog.CloseTrigger class={noStyle ? '' : styles.closeButton || ''} aria-label="Close">
						<CloseIcon width="16" height="16" aria-hidden={true} />
					</Dialog.CloseTrigger>
				</div>

				<Tabs.Root
					value={activeTab}
					onValueChange={handleTabChange}
					class={noStyle ? '' : styles.body || ''}
				>
					<div class={noStyle ? '' : styles.tabsContainer || ''}>
						<Tabs.List class={noStyle ? '' : styles.tabsList || ''}>
							<Tabs.Trigger value="purposes" class={noStyle ? '' : styles.tabButton || ''}>
								{iabT.preferenceCenter.tabs.purposes}
								{#if !isLoading && gvlData}
									({gvlData.purposes.length +
										gvlData.specialPurposes.length +
										gvlData.specialFeatures.length +
										gvlData.features.length})
								{/if}
							</Tabs.Trigger>
							<Tabs.Trigger value="vendors" class={noStyle ? '' : styles.tabButton || ''}>
								{iabT.preferenceCenter.tabs.vendors}
								{#if !isLoading}
									({totalVendors})
								{/if}
							</Tabs.Trigger>
							<div
								aria-hidden="true"
								class={noStyle ? '' : styles.tabIndicator || ''}
								data-active-tab={activeTab}
							></div>
						</Tabs.List>
					</div>

					<div class={noStyle ? '' : styles.content || ''}>
						<Tabs.Content value="purposes" forceMount class={noStyle ? '' : styles.tabPanel || ''}>
						{#if isLoading}
							<div class={noStyle ? '' : styles.loadingContainer || ''}>
								<div class={noStyle ? '' : styles.loadingSpinner || ''}></div>
								<p class={noStyle ? '' : styles.loadingText || ''}>
									{iabT.common.loading}
								</p>
							</div>
						{:else if gvlData && iabState}
							<!-- Standalone purposes -->
							{#each gvlData.standalonePurposes as purpose (purpose.id)}
								<IABPurposeItem
									{purpose}
									isEnabled={iabState.purposeConsents[purpose.id] ?? false}
									onToggle={(value) => handlePurposeToggle(purpose.id, value)}
									vendorConsents={iabState.vendorConsents}
									onVendorToggle={handleVendorToggle}
									onVendorClick={handleVendorClick}
									vendorLegitimateInterests={iabState.vendorLegitimateInterests}
									onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
									purposeLegitimateInterests={iabState.purposeLegitimateInterests}
									onPurposeLegitimateInterestToggle={handlePurposeLegitimateInterestToggle}
									{noStyle}
									{iabT}
								/>
							{/each}

							<!-- Stacks -->
							{#each gvlData.stacks as stack (stack.id)}
								<IABStackItem
									{stack}
									consents={iabState.purposeConsents}
									onToggle={handlePurposeToggle}
									vendorConsents={iabState.vendorConsents}
									onVendorToggle={handleVendorToggle}
									onVendorClick={handleVendorClick}
									vendorLegitimateInterests={iabState.vendorLegitimateInterests}
									onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
									purposeLegitimateInterests={iabState.purposeLegitimateInterests}
									onPurposeLegitimateInterestToggle={handlePurposeLegitimateInterestToggle}
									{noStyle}
									{iabT}
								/>
							{/each}

							<!-- Special Features -->
							{#each gvlData.specialFeatures as feature (feature.id)}
								<IABPurposeItem
									purpose={{
										id: feature.id,
										name: feature.name,
										description: feature.description,
										illustrations: feature.illustrations,
										vendors: feature.vendors,
									}}
									isEnabled={iabState.specialFeatureOptIns[feature.id] ?? false}
									onToggle={(value) => handleSpecialFeatureToggle(feature.id, value)}
									vendorConsents={iabState.vendorConsents}
									onVendorToggle={handleVendorToggle}
									onVendorClick={handleVendorClick}
									vendorLegitimateInterests={iabState.vendorLegitimateInterests}
									onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
									{noStyle}
									{iabT}
								/>
							{/each}

							<!-- Essential Functions: Special Purposes + Features (locked) -->
							{#if gvlData.specialPurposes.length > 0 || gvlData.features.length > 0}
								<Collapsible.Root
									open={specialPurposesExpanded}
									onOpenChange={(details) => {
										specialPurposesExpanded = details.open;
									}}
									class={noStyle ? '' : styles.specialPurposesSection || ''}
								>
									<div class={noStyle ? '' : styles.specialPurposesHeader || ''}>
										<Collapsible.Trigger class={noStyle ? '' : styles.purposeTrigger || ''}>
											<Collapsible.Indicator class={noStyle ? '' : styles.purposeArrow || ''}>
												<ChevronRightIcon aria-hidden={true} />
											</Collapsible.Indicator>
											<div class={noStyle ? '' : styles.purposeInfo || ''}>
												<h3 class={noStyle ? '' : styles.specialPurposesTitle || ''}>
													{iabT.preferenceCenter.specialPurposes.title}
													<LockIcon
														class={noStyle ? '' : styles.lockIcon || ''}
														aria-hidden={true}
													/>
												</h3>
												<p class={noStyle ? '' : styles.purposeMeta || ''}>
													{specialSectionPartnerCount}
													{specialSectionPartnerCount === 1
														? iabT.preferenceCenter.vendorList.partnerSingular
														: iabT.preferenceCenter.vendorList.partnerPlural}
												</p>
											</div>
										</Collapsible.Trigger>
										<InfoIcon
											class={noStyle ? '' : styles.infoIcon || ''}
											aria-label={iabT.preferenceCenter.specialPurposes.tooltip}
										/>
									</div>

									<Collapsible.Content>
										<div>
											<!-- Special Purposes -->
											{#each gvlData.specialPurposes as purpose (purpose.id)}
												<IABPurposeItem
													{purpose}
													isEnabled={true}
													onToggle={() => {}}
													vendorConsents={iabState.vendorConsents}
													onVendorToggle={handleVendorToggle}
													onVendorClick={handleVendorClick}
													isLocked={true}
													{noStyle}
													{iabT}
												/>
											{/each}

											<!-- Features -->
											{#each gvlData.features as feature (feature.id)}
												<IABPurposeItem
													purpose={{
														id: feature.id,
														name: feature.name,
														description: feature.description,
														illustrations: feature.illustrations,
														vendors: feature.vendors,
													}}
													isEnabled={true}
													onToggle={() => {}}
													vendorConsents={iabState.vendorConsents}
													onVendorToggle={handleVendorToggle}
													onVendorClick={handleVendorClick}
													isLocked={true}
													{noStyle}
													{iabT}
												/>
											{/each}
										</div>
									</Collapsible.Content>
								</Collapsible.Root>
							{/if}

							<!-- Consent storage notice -->
							<div class={noStyle ? '' : styles.consentNotice || ''}>
								<p class={noStyle ? '' : styles.consentNoticeText || ''}>
									{iabT.preferenceCenter.footer.consentStorage}
								</p>
							</div>
						{/if}
						</Tabs.Content>

						<Tabs.Content value="vendors" forceMount class={noStyle ? '' : styles.tabPanel || ''}>
						{#if iabState}
							<IABVendorList
								vendorData={iabState.gvl}
								purposes={gvlData?.purposes ?? []}
								vendorConsents={iabState.vendorConsents}
								onVendorToggle={handleVendorToggle}
								{selectedVendorId}
								onClearSelection={() => (selectedVendorId = null)}
								customVendors={iabState.nonIABVendors}
								vendorLegitimateInterests={iabState.vendorLegitimateInterests}
								onVendorLegitimateInterestToggle={handleVendorLegitimateInterestToggle}
								{noStyle}
								{iabT}
							/>
						{/if}
						</Tabs.Content>
					</div>
				</Tabs.Root>

				<!-- Footer -->
				<div class={noStyle ? '' : styles.footer || ''}>
					<div class={noStyle ? '' : styles.footerButtons || ''}>
						<button
							type="button"
							class={noStyle ? '' : styles.footerButton || ''}
							onclick={handleRejectAll}
							disabled={isLoading}
						>
							{iabT.common.rejectAll}
						</button>
						<button
							type="button"
							class={noStyle ? '' : styles.footerButton || ''}
							onclick={handleAcceptAll}
							disabled={isLoading}
						>
							{iabT.common.acceptAll}
						</button>
					</div>
					<div class={noStyle ? '' : styles.footerSpacer || ''}></div>
					<button
						type="button"
						class={noStyle
							? ''
							: `${styles.footerButton || ''} ${styles.footerButtonPrimary || ''}`}
						onclick={handleSave}
						disabled={isLoading}
					>
						{iabT.common.saveSettings}
					</button>
				</div>
				<Branding
					{hideBranding}
					{noStyle}
					variant="dialog-tag"
					themeKey="iabConsentDialogTag"
					data-testid="iab-consent-dialog-branding"
				/>
			</Dialog.Content>
		</Dialog.Positioner>
	</Portal>
</Dialog.Root>
